//
//  MockData.swift
//  TwoScreens
//
//  Created by artyom s on 09.08.2024.
//

import SwiftUI

var mockData: [ItemModel] = [
    ItemModel(image: .init(value: .init(.image1),
                           imagedecorationText: "Вксновато",
                           imagedecorationType: .agressive,
                           discountValue: 20),
              score: 4.1,
              reviewCount: 159,
              description: "сыр Ламбер 500/0 230г",
              country: "Россия",
              price: 300,
              previousPrice: 499),
    ItemModel(image: .init(value: .init(.image2),
                           imagedecorationText: "Скидка!",
                           imagedecorationType: .calm,
                           discountValue: 99),
              score: 4.4,
              reviewCount: 77,
              description: "Энергетический Напит",
              country: "Россия",
              price: 100,
              previousPrice: 199),
    ItemModel(image: .init(value:  .init(.image3),
                  imagedecorationText: "",
                  imagedecorationType: .none,
                  discountValue: 32),
              
                  score: 4.4,
                  reviewCount: 66,
                  description: "Дорадо Охлажденная Непотрошеная 300-400г",
                  country: "Россия",
                  price: 300,
                  previousPrice: 499),
    
    ItemModel(image: .init(value: .init(.image4),
                  imagedecorationText: "",
                  imagedecorationType: .none,
                  discountValue: 14),
                  score: 4.7,
                  reviewCount: 12,
                  description: "Салат Овощной с Крабовыми Палочками",
                  country: "Россия",
                  price: 300,
                  previousPrice: 499),
              
    ItemModel(image: .init(value: .init(.image5),
                  imagedecorationText: "",
                  imagedecorationType: .none,
                  discountValue: 0),
                  score: 4.4,
                  reviewCount: 64,
                  description: "Ролл Маленькая Япония 216г",
                  country: "Россия",
                  price: 300,
                  previousPrice: 499),
              
    ItemModel(image: .init(value: .init(.image6),
                  imagedecorationText: "",
                  imagedecorationType: .none,
                  discountValue: 0),
                  score: 4.1,
                  reviewCount: 1,
                  description: "Огурцы тепличные cадово-огородные",
                  country: "Россия",
                  price: 300,
                  previousPrice: 499),
              
    ItemModel(image: .init(value: .init(.image7),
                  imagedecorationText: "",
                  imagedecorationType: .none,
                  discountValue: 0),
                  score: 4.6,
                  reviewCount: 37,
                  description: "Манго Кео",
                  country: "Россия",
                  price: 300,
                  previousPrice: 499),
              
    ItemModel(image: .init(value: .init(.image8),
                  imagedecorationText: "",
                  imagedecorationType: .none,
                  discountValue: 0),
                  score: 2.4,
                  reviewCount: 8,
                  description: "Салат Овощной с Крабовыми Палочками",
                  country: "Россия",
                  price: 300,
                  previousPrice: 499),
              
    ItemModel(image: .init(value: .init(.image9),
                  imagedecorationText: "ЖЖетт!",
                  imagedecorationType: .agressive,
                  discountValue: 0),
                  score: 3.4,
                  reviewCount: 5,
                  description: "Масло Слобода Рафинированное 1,8л",
                  country: "Россия",
                  price: 300,
                  previousPrice: 499),
              
    ItemModel(image: .init(value: .init(.image10),
                  imagedecorationText: "",
                  imagedecorationType: .none,
                  discountValue: 0),
                  score: 4.8,
                  reviewCount: 9,
                  description: "Макаронные Изделия SPAR Спагетти 450г",
                  country: "Россия",
                  price: 300,
                  previousPrice: 499),
              
    ItemModel(image: .init(value: .init(.image11),
                  imagedecorationText: "",
                  imagedecorationType: .none,
                  discountValue: 21),
                  score: 4.1,
                  reviewCount: 27,
                  description: "сыр Моцарелла 200/0 130г сыр Моцарелла 200/0 130г сыр Моцарелла 200/0 130г сыр Моцарелла 200/0 130г",
                  country: "Россия",
                  price: 300,
                  previousPrice: 499),
              
    ItemModel(image: .init(value: .init(.image12),
                  imagedecorationText: "Вкусно",
                  imagedecorationType: .neutral,
                  discountValue: 0),
                  score: 3.4,
                  reviewCount: 3,
                  description: "абрикосы армянские",
                  country: "Армения",
                  price: 300,
                  previousPrice: 499),
              
    ItemModel(image: .init(value: .init(.image13),
                  imagedecorationText: "",
                  imagedecorationType: .none,
                  discountValue: 11),
                  score: 4.8,
                  reviewCount: 48,
                  description: "сыр Швецарский",
                  country: "Швеция",
                  price: 300,
                  previousPrice: 1999),
    ItemModel(image: .init(value: .init(.image14),
                  imagedecorationText: "Пуруруру",
                  imagedecorationType: .calm,
                  discountValue: 0),
                  score: 4.6,
                  reviewCount: 45,
                  description: "Хамон Испанский",
                  country: "Испания",
                  price: 300,
                  previousPrice: 499),
    ItemModel(image: .init(value: .init(.image15),
                  imagedecorationText: "",
                  imagedecorationType: .none,
                  discountValue: 0),
                  score: 4.3,
                  reviewCount: 13,
                  description: "Колбаса варенная",
                  country: "Россия",
                  price: 300,
                  previousPrice: 499),
    ItemModel(image: .init(value: .init(.image16),
                  imagedecorationText: "Спецпредложение!",
                  imagedecorationType: .calm,
                  discountValue: 0),
                  score: 4.3,
                  reviewCount: 22,
                  description: "Блинчики со сплеой вишней",
                  country: "Россия",
                  price: 300,
                  previousPrice: 499),
    ItemModel(image: .init(value: .init(.image17),
                  imagedecorationText: "",
                  imagedecorationType: .none,
                  discountValue: 0),
                  score: 4.2,
                  reviewCount: 19,
                  description: "РОлл запеченный с горбушей",
                  country: "Россия",
                  price: 300,
                  previousPrice: 499),
    ItemModel(image: .init(value: .init(.image18),
                  imagedecorationText: "Новинка",
                  imagedecorationType: .neutral,
                  discountValue: 0),
                  score: 4.1,
                  reviewCount: 18,
                  description: "Сет филаделфия Микс 850г",
                  country: "Россия",
                  price: 300,
                  previousPrice: 499)
]
